slogo_team14: view.panes.ButtonPaneModule Class Reference
view.panes.ButtonPaneModule Class Reference
Public Member Functions
ButtonPaneModule (CommandString cs, LanguageController ls, ViewPaneModule vs, VBox v)
void createPropertiesMenu ()
BorderPane addPane (BorderPane p)
void backgroundColor ()
void toggleGrid ()
void help ()
Public Member Functions inherited from view.panes.PaneModule
abstract BorderPane addPane (BorderPane p)
Private Member Functions
Button makeButton (String property, EventHandler< ActionEvent > handler)
ColorPicker makeColorPicker (String property, EventHandler< ActionEvent > handler)
Private Attributes
final ToolBar myToolBar = new ToolBar()
HBox myHbox = new HBox()
CommandString myCommandString
ColorPicker myColorPicker
LanguageController myLanguageController
ViewPaneModule myView
VBox myVBox
Detailed Description
Pane containing the ToolBar of Buttons allowing for function setting
Author
Team 14
Definition at line 27 of file ButtonPaneModule.java.
Constructor & Destructor Documentation
view.panes.ButtonPaneModule.ButtonPaneModule (CommandString cs, LanguageController ls, ViewPaneModule vs, VBox v)
Definition at line 36 of file ButtonPaneModule.java.
References view.panes.ButtonPaneModule.createPropertiesMenu().
Member Function Documentation
BorderPane view.panes.ButtonPaneModule.addPane (BorderPane p)
Adds the pane to the BorderPane
Definition at line 60 of file ButtonPaneModule.java.
void view.panes.ButtonPaneModule.backgroundColor ()
Sets the background color using a colorpicker
Definition at line 109 of file ButtonPaneModule.java.
References view.CommandString.setCommand(), and view.Constants.SETTING.
Referenced by view.panes.ButtonPaneModule.createPropertiesMenu().
void view.panes.ButtonPaneModule.createPropertiesMenu ()
Creates the Toolbar of Buttons that allow for Properties adjustment
Definition at line 47 of file ButtonPaneModule.java.
References view.panes.ButtonPaneModule.backgroundColor(), view.panes.ButtonPaneModule.help(), view.panes.ButtonPaneModule.makeButton(), view.panes.ButtonPaneModule.makeColorPicker(), view.controllers.LanguageController.makeMenu(), and view.panes.ButtonPaneModule.toggleGrid().
Referenced by view.panes.ButtonPaneModule.ButtonPaneModule().
void view.panes.ButtonPaneModule.help ()
Allows for the opening of a help page in an Internet Browser
Definition at line 127 of file ButtonPaneModule.java.
References view.Constants.HELP_URL.
Referenced by view.panes.ButtonPaneModule.createPropertiesMenu().
Button view.panes.ButtonPaneModule.makeButton (String property, EventHandler< ActionEvent > handler) private
Button Factory
Parameters
property String label for button
handler EventHandler for the button
Returns
Completed Button
Definition at line 81 of file ButtonPaneModule.java.
Referenced by view.panes.ButtonPaneModule.createPropertiesMenu().
ColorPicker view.panes.ButtonPaneModule.makeColorPicker (String property, EventHandler< ActionEvent > handler) private
ColorPicker Factory
Parameters
property String label for ColorPicker
handler EventHandler for ColorPicker
Returns
Completed ColorPicker
Definition at line 98 of file ButtonPaneModule.java.
Referenced by view.panes.ButtonPaneModule.createPropertiesMenu().
void view.panes.ButtonPaneModule.toggleGrid ()
Toggles the visibility of the Grid
Definition at line 120 of file ButtonPaneModule.java.
References view.panes.ViewPaneModule.changeGridVisibility().
Referenced by view.panes.ButtonPaneModule.createPropertiesMenu().
Member Data Documentation
ColorPicker view.panes.ButtonPaneModule.myColorPicker private
Definition at line 31 of file ButtonPaneModule.java.
CommandString view.panes.ButtonPaneModule.myCommandString private
Definition at line 30 of file ButtonPaneModule.java.
HBox view.panes.ButtonPaneModule.myHbox = new HBox() private
Definition at line 29 of file ButtonPaneModule.java.
LanguageController view.panes.ButtonPaneModule.myLanguageController private
Definition at line 32 of file ButtonPaneModule.java.
final ToolBar view.panes.ButtonPaneModule.myToolBar = new ToolBar() private
Definition at line 28 of file ButtonPaneModule.java.
VBox view.panes.ButtonPaneModule.myVBox private
Definition at line 34 of file ButtonPaneModule.java.
ViewPaneModule view.panes.ButtonPaneModule.myView private
Definition at line 33 of file ButtonPaneModule.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/panes/ButtonPaneModule.java