slogo_team14: model.VariableManager Class Reference
model.VariableManager Class Reference
Public Member Functions
VariableManager ()
void addVariableMap (Map< String, Double > newMap)
void reduceVariableScope ()
Map< String, Double > getGlobalVariables ()
Map< String, Double > getLocalVariables ()
void addGlobalVariable (String varName, double varValue)
void addLocalVariable (String varName, double varValue)
int getVariableScope ()
Private Attributes
Map< String, Double > myGlobalVariables
Stack< Map< String, Double > > myLocalVariables
Detailed Description
Definition at line 8 of file VariableManager.java.
Constructor & Destructor Documentation
model.VariableManager.VariableManager ()
Definition at line 15 of file VariableManager.java.
Member Function Documentation
void model.VariableManager.addGlobalVariable (String varName, double varValue)
Method to add a global variable.
Parameters
varName,varValue : String and double corresponding to variable and its value.
Definition at line 54 of file VariableManager.java.
Referenced by commands.MakeVariableCommand.executeCommand().
void model.VariableManager.addLocalVariable (String varName, double varValue)
same as above, but for local variables
Definition at line 60 of file VariableManager.java.
Referenced by commands.DoTimesCommand.executeCommand(), and commands.ForCommand.executeCommand().
void model.VariableManager.addVariableMap (Map< String, Double > newMap)
Method to add a map to the stack.
Parameters
newMap : map to be added to the stack.
Definition at line 25 of file VariableManager.java.
Referenced by commands.DoTimesCommand.executeCommand(), commands.ForCommand.executeCommand(), and commands.CustomCommand.executeCommand().
Map<String, Double> model.VariableManager.getGlobalVariables ()
Method to get the global variables.
Definition at line 39 of file VariableManager.java.
References model.VariableManager.myGlobalVariables.
Referenced by commands.VariableCommand.executeCommand().
Map<String, Double> model.VariableManager.getLocalVariables ()
Method to get the local variables only.
Definition at line 45 of file VariableManager.java.
Referenced by commands.VariableCommand.executeCommand().
int model.VariableManager.getVariableScope ()
Definition at line 66 of file VariableManager.java.
Referenced by commands.VariableCommand.executeCommand().
void model.VariableManager.reduceVariableScope ()
Method to reduce the length of the stack by one to reduce scope
Definition at line 31 of file VariableManager.java.
Referenced by commands.DoTimesCommand.executeCommand(), commands.ForCommand.executeCommand(), and commands.CustomCommand.executeCommand().
Member Data Documentation
Map<String, Double> model.VariableManager.myGlobalVariables private
Class used to manage variables and scope
Definition at line 12 of file VariableManager.java.
Referenced by model.VariableManager.getGlobalVariables().
Stack<Map<String, Double> > model.VariableManager.myLocalVariables private
Definition at line 13 of file VariableManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/model/VariableManager.java