slogo_team14: view.controllers.ImagePalette Class Reference
view.controllers.ImagePalette Class Reference
Public Member Functions
ImagePalette ()
void addImage (String s, String f)
String getImage (int i)
String getCurrentImage ()
int getCurrentImageID ()
ChoiceBox< String > getBox ()
Private Attributes
Map< Integer, String > myImages = new HashMap<Integer, String>()
List< String > myChoices = new ArrayList<String>()
ObservableList< String > myObservable = FXCollections.observableList(myChoices)
ChoiceBox< String > myChoiceImages = new ChoiceBox<String>(myObservable)
String myCurrentImage = TURTLE
int myCurrentImageID
Static Private Attributes
static final String TURTLE = "/resources/images/LogoTurtle2.png"
static final String TRIANGLE = "/resources/images/Triangle.png"
static final String CIRCLE = "/resources/images/Circle.png"
static final String DUVALL = "/resources/images/RCD.png"
Detailed Description
Contains a Palette of images that can be used to set turtle images
Author
Team 14
Definition at line 20 of file ImagePalette.java.
Constructor & Destructor Documentation
view.controllers.ImagePalette.ImagePalette ()
Default Constructor. Populates with default image options.
Definition at line 35 of file ImagePalette.java.
Member Function Documentation
void view.controllers.ImagePalette.addImage (String s, String f)
Adds an image to the palette
Parameters
s String containing the file path to image
f String containing the name of the new image
Definition at line 64 of file ImagePalette.java.
Referenced by view.panes.TurtleControllerPaneModule.doChoose().
ChoiceBox<String> view.controllers.ImagePalette.getBox ()
Getter to get the ChoiceBox with the Image options
Returns
ChoiceBox with the Image options
Definition at line 103 of file ImagePalette.java.
References view.controllers.ImagePalette.myChoiceImages.
Referenced by view.panes.TurtleControllerPaneModule.imageSelectorMaker().
String view.controllers.ImagePalette.getCurrentImage ()
Getter for the current image set
Returns
String containing file path to image
Definition at line 85 of file ImagePalette.java.
References view.controllers.ImagePalette.myCurrentImage.
int view.controllers.ImagePalette.getCurrentImageID ()
Getter for the current image ID
Returns
ID representing current image ID
Definition at line 94 of file ImagePalette.java.
References view.controllers.ImagePalette.myCurrentImageID.
Referenced by view.panes.TurtleControllerPaneModule.makeTurtle().
String view.controllers.ImagePalette.getImage (int i)
Gets an image file path from the palette
Parameters
i int representing ID of image
Returns
String containing file path to image
Definition at line 76 of file ImagePalette.java.
Referenced by view.TurtleDraw.drawTurtle().
Member Data Documentation
final String view.controllers.ImagePalette.CIRCLE = "/resources/images/Circle.png" static private
Definition at line 23 of file ImagePalette.java.
final String view.controllers.ImagePalette.DUVALL = "/resources/images/RCD.png" static private
Definition at line 24 of file ImagePalette.java.
ChoiceBox<String> view.controllers.ImagePalette.myChoiceImages = new ChoiceBox<String>(myObservable) private
Definition at line 28 of file ImagePalette.java.
Referenced by view.controllers.ImagePalette.getBox().
List<String> view.controllers.ImagePalette.myChoices = new ArrayList<String>() private
Definition at line 26 of file ImagePalette.java.
String view.controllers.ImagePalette.myCurrentImage = TURTLE private
Definition at line 29 of file ImagePalette.java.
Referenced by view.controllers.ImagePalette.getCurrentImage().
int view.controllers.ImagePalette.myCurrentImageID private
Definition at line 30 of file ImagePalette.java.
Referenced by view.controllers.ImagePalette.getCurrentImageID().
Map<Integer, String> view.controllers.ImagePalette.myImages = new HashMap<Integer, String>() private
Definition at line 25 of file ImagePalette.java.
ObservableList<String> view.controllers.ImagePalette.myObservable = FXCollections.observableList(myChoices) private
Definition at line 27 of file ImagePalette.java.
final String view.controllers.ImagePalette.TRIANGLE = "/resources/images/Triangle.png" static private
Definition at line 22 of file ImagePalette.java.
final String view.controllers.ImagePalette.TURTLE = "/resources/images/LogoTurtle2.png" static private
Definition at line 21 of file ImagePalette.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/controllers/ImagePalette.java