slogo_team14: commands.Command Class Reference
commands.Command Class Reference abstract
Public Member Functions
Command ()
Command (int numParameters)
int getNumParameters ()
void setParameters (Command[] parameters)
Command getParameter (int index)
double executeCommand (Model model)
String getClassName ()
Protected Member Functions
double updateTurtle (Model model, Turtle a)
Turtle getFirstTurtle (Model model)
Protected Attributes
Command[] myParameters
Detailed Description
Command class which all the other sub command classes extend
Author
team14
Definition at line 13 of file Command.java.
Constructor & Destructor Documentation
commands.Command.Command ()
Constructor for Command object with no input
Definition at line 20 of file Command.java.
commands.Command.Command (int numParameters)
Constructor for Command object with one or more than one input
Parameters
numParameters - number of parameters
Definition at line 28 of file Command.java.
Member Function Documentation
double commands.Command.executeCommand (Model model)
This method executes a specific command on each turtle in the given model
Parameters
model - contains all the active turtles
Returns
the last turtle on which command was executed
Definition at line 52 of file Command.java.
References model.TurtleSetManager.getActiveTurtles(), model.Model.getTurtleManager(), model.Model.notifyView(), and commands.Command.updateTurtle().
Referenced by commands.SumCommand.executeCommand(), commands.RepeatCommand.executeCommand(), commands.RemainderCommand.executeCommand(), commands.MinusCommand.executeCommand(), commands.SetBackgroundCommand.executeCommand(), commands.ProductCommand.executeCommand(), commands.QuotientCommand.executeCommand(), commands.MakeVariableCommand.executeCommand(), commands.DifferenceCommand.executeCommand(), commands.ClearScreenCommand.executeCommand(), commands.AskCommand.executeCommand(), commands.IfElseCommand.executeCommand(), commands.ForCommand.executeCommand(), commands.AskWithCommand.executeCommand(), commands.DoTimesCommand.executeCommand(), commands.CustomCommand.executeCommand(), commands.SetShapeCommand.updateTurtle(), commands.SetPenDashCommand.updateTurtle(), commands.SetTowardsCommand.updateTurtle(), commands.SetPositionCommand.updateTurtle(), commands.RightCommand.updateTurtle(), commands.SetHeadingCommand.updateTurtle(), commands.SetPenSizeCommand.updateTurtle(), commands.SetPenColorCommand.updateTurtle(), commands.LeftCommand.updateTurtle(), commands.BackwardCommand.updateTurtle(), and commands.ForwardCommand.updateTurtle().
String commands.Command.getClassName ()
Definition at line 69 of file Command.java.
Referenced by commands.MakeUserInstructionCommand.executeCommand(), commands.CustomCommand.executeCommand(), and parser.Parser.parseInput().
Turtle commands.Command.getFirstTurtle (Model model) protected
Definition at line 65 of file Command.java.
References model.TurtleSetManager.getActiveTurtles(), and model.Model.getTurtleManager().
Referenced by commands.YCoordinateCommand.executeCommand(), commands.XCoordinateCommand.executeCommand(), commands.HeadingCommand.executeCommand(), commands.IsShowingCommand.executeCommand(), commands.IsPenDownCommand.executeCommand(), commands.IDCommand.executeCommand(), commands.GetShapeCommand.executeCommand(), and commands.GetPenColorCommand.executeCommand().
int commands.Command.getNumParameters ()
Definition at line 32 of file Command.java.
Referenced by parser.Parser.getCommand().
Command commands.Command.getParameter (int index)
Definition at line 42 of file Command.java.
Referenced by commands.MakeUserInstructionCommand.executeCommand(), and commands.CustomCommand.executeCommand().
void commands.Command.setParameters (Command[] parameters)
Definition at line 36 of file Command.java.
Referenced by commands.AskCommand.executeCommand(), commands.IfCommand.executeCommand(), commands.AskWithCommand.executeCommand(), and parser.Parser.getCommand().
double commands.Command.updateTurtle (Model model, Turtle a) protected
Definition at line 61 of file Command.java.
Referenced by commands.Command.executeCommand().
Member Data Documentation
Command [] commands.Command.myParameters protected
Definition at line 15 of file Command.java.
Referenced by commands.SineCommand.executeCommand(), commands.SumCommand.executeCommand(), commands.TangentCommand.executeCommand(), commands.NotEqualCommand.executeCommand(), commands.RemainderCommand.executeCommand(), commands.RepeatCommand.executeCommand(), commands.LessThanCommand.executeCommand(), commands.SetBackgroundCommand.executeCommand(), commands.ArcTangentCommand.executeCommand(), commands.NaturalLogCommand.executeCommand(), commands.AndCommand.executeCommand(), commands.MinusCommand.executeCommand(), commands.NotCommand.executeCommand(), commands.PowerCommand.executeCommand(), commands.ProductCommand.executeCommand(), commands.QuotientCommand.executeCommand(), commands.OrCommand.executeCommand(), commands.DifferenceCommand.executeCommand(), commands.MakeVariableCommand.executeCommand(), commands.EqualCommand.executeCommand(), commands.CosineCommand.executeCommand(), commands.RandomCommand.executeCommand(), commands.AskCommand.executeCommand(), commands.GreaterThanCommand.executeCommand(), commands.IfCommand.executeCommand(), commands.IfElseCommand.executeCommand(), commands.TellCommand.executeCommand(), commands.AskWithCommand.executeCommand(), commands.DoTimesCommand.executeCommand(), commands.ForCommand.executeCommand(), commands.MakeUserInstructionCommand.executeCommand(), commands.CustomCommand.executeCommand(), commands.SetShapeCommand.updateTurtle(), commands.RightCommand.updateTurtle(), commands.SetPositionCommand.updateTurtle(), commands.SetTowardsCommand.updateTurtle(), commands.SetHeadingCommand.updateTurtle(), commands.SetPenSizeCommand.updateTurtle(), commands.SetPenColorCommand.updateTurtle(), commands.SetPenDashCommand.updateTurtle(), commands.LeftCommand.updateTurtle(), commands.BackwardCommand.updateTurtle(), and commands.ForwardCommand.updateTurtle().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/commands/Command.java