slogo_team14: model.Pen Class Reference
model.Pen Class Reference
Public Member Functions
Pen ()
Protected Member Functions
double updateSize (double newSize)
double updateDash (double newDash)
double getSize ()
double getDash ()
double updateColor (double red, double green, double blue)
double getColor ()
Color getPenColor ()
double setPenStatus (double status)
double getStatus ()
Private Attributes
Color myColor
double mySize
double myDash
double isPenDown
Static Private Attributes
static final int BLUE_CONSTANT = 255000000
static final int GREEN_CONSTANT = 255000
static final int RED_CONSTANT = 255
Detailed Description
Class the contains the pen information, instantiated for each turtle because each turtle can have different pen information
Definition at line 9 of file Pen.java.
Constructor & Destructor Documentation
model.Pen.Pen ()
Definition at line 18 of file Pen.java.
Member Function Documentation
double model.Pen.getColor () protected
Method to return the Color of the pen to the turtle in which the pen is contained in the form of a double that can be easily interpreted.
Definition at line 79 of file Pen.java.
References model.Pen.BLUE_CONSTANT, model.Pen.GREEN_CONSTANT, and model.Pen.RED_CONSTANT.
double model.Pen.getDash () protected
Method to return whether or not the line is dashed to the turtle the pen is contained in
Definition at line 57 of file Pen.java.
References model.Pen.myDash.
Referenced by model.Turtle.getPenDash().
Color model.Pen.getPenColor () protected
Method to return the Color of the pen to the turtle as a color.
Definition at line 89 of file Pen.java.
References model.Pen.myColor.
Referenced by model.Turtle.getPenColor().
double model.Pen.getSize () protected
Method to return the size of the pen to the Turtle the pen is contained in
Definition at line 49 of file Pen.java.
References model.Pen.mySize.
Referenced by model.Turtle.getPenSize().
double model.Pen.getStatus () protected
Method to return to the turtle whether or not the pen is up.
Definition at line 107 of file Pen.java.
References model.Pen.isPenDown.
Referenced by model.Turtle.changePen(), and model.Turtle.getPenStatus().
double model.Pen.setPenStatus (double status) protected
Method to set whether or not the pen is down.
Parameters
status : double that indicates whether the pen is up or not.
Definition at line 99 of file Pen.java.
Referenced by model.Turtle.changePen().
double model.Pen.updateColor (double red, double green, double blue) protected
Method to update the color of the pen.
Parameters
red,blue,green amount of red, blue, green in the new color
Definition at line 67 of file Pen.java.
Referenced by model.Turtle.setPenColor().
double model.Pen.updateDash (double newDash) protected
Method to update whether the line is solid or dashed.
Parameters
double newDash : tells you whether or not the line is dashed
Definition at line 39 of file Pen.java.
Referenced by model.Turtle.setPenDash().
double model.Pen.updateSize (double newSize) protected
Method to update the size of the pen.
Parameters
double newSize : new size pen should be
Definition at line 29 of file Pen.java.
Referenced by model.Turtle.setPenSize().
Member Data Documentation
final int model.Pen.BLUE_CONSTANT = 255000000 static private
Definition at line 10 of file Pen.java.
Referenced by model.Pen.getColor().
final int model.Pen.GREEN_CONSTANT = 255000 static private
Definition at line 11 of file Pen.java.
Referenced by model.Pen.getColor().
double model.Pen.isPenDown private
Definition at line 16 of file Pen.java.
Referenced by model.Pen.getStatus().
Color model.Pen.myColor private
Definition at line 13 of file Pen.java.
Referenced by model.Pen.getPenColor().
double model.Pen.myDash private
Definition at line 15 of file Pen.java.
Referenced by model.Pen.getDash().
double model.Pen.mySize private
Definition at line 14 of file Pen.java.
Referenced by model.Pen.getSize().
final int model.Pen.RED_CONSTANT = 255 static private
Definition at line 12 of file Pen.java.
Referenced by model.Pen.getColor().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/model/Pen.java