slogo_team14: view.panes.InputPaneModule Class Reference
view.panes.InputPaneModule Class Reference
Classes
class SubmitHandler
Public Member Functions
InputPaneModule (CommandString cs)
BorderPane addPane (BorderPane p)
Public Member Functions inherited from view.panes.PaneModule
abstract BorderPane addPane (BorderPane p)
Private Member Functions
void submit ()
void save ()
Private Attributes
HBox myHBox = new HBox()
ScrollPane myScrollPane = new ScrollPane()
TextField myTextField = new TextField()
CommandString myCommandString
Detailed Description
Subclass of Pane that implements a scrollable textfield that allows for user input. Hitting enter or hitting the submit button pushes the command inputed by the user.
Author
Team14
Definition at line 23 of file InputPaneModule.java.
Constructor & Destructor Documentation
view.panes.InputPaneModule.InputPaneModule (CommandString cs)
Initializes the parameters of the InputPane.
Parameters
cs CommandString containing the String that represents the current command
Definition at line 36 of file InputPaneModule.java.
References view.panes.InputPaneModule.save(), and view.panes.InputPaneModule.submit().
Member Function Documentation
BorderPane view.panes.InputPaneModule.addPane (BorderPane p)
Adds the pane to the BorderPane
Definition at line 76 of file InputPaneModule.java.
void view.panes.InputPaneModule.save () private
Saves the current command as a user defined command for future use by update the CommandString with the String contained by the TextField.
Definition at line 64 of file InputPaneModule.java.
References view.CommandString.setCommand(), and view.Constants.USER_DEFINE.
Referenced by view.panes.InputPaneModule.InputPaneModule().
void view.panes.InputPaneModule.submit () private
Submits the current command by updating the CommandString with the String contained by the TextField. Then clear the field in preparation for the next command.
Definition at line 53 of file InputPaneModule.java.
References view.Constants.COMMAND, and view.CommandString.setCommand().
Referenced by view.panes.InputPaneModule.SubmitHandler.handle(), and view.panes.InputPaneModule.InputPaneModule().
Member Data Documentation
CommandString view.panes.InputPaneModule.myCommandString private
Definition at line 27 of file InputPaneModule.java.
HBox view.panes.InputPaneModule.myHBox = new HBox() private
Definition at line 24 of file InputPaneModule.java.
ScrollPane view.panes.InputPaneModule.myScrollPane = new ScrollPane() private
Definition at line 25 of file InputPaneModule.java.
TextField view.panes.InputPaneModule.myTextField = new TextField() private
Definition at line 26 of file InputPaneModule.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/panes/InputPaneModule.java