slogo_team14: view.controllers.WorkspaceTabsController Class Reference
view.controllers.WorkspaceTabsController Class Reference
Public Member Functions
WorkspaceTabsController (BorderPane bp)
Private Member Functions
void newTab ()
void makeActive (Tab t1)
Private Attributes
HBox myHbox = new HBox()
TabPane myTabPane = new TabPane()
List< PaneController > myWorkspaces = new ArrayList<PaneController>()
BorderPane myBorderPane
VBox myVBox = new VBox()
Detailed Description
Maintains multiple workspaces within the program. Allows for creation of new workspace and switching between existing workspaces.
Author
Team 14
Definition at line 22 of file WorkspaceTabsController.java.
Constructor & Destructor Documentation
view.controllers.WorkspaceTabsController.WorkspaceTabsController (BorderPane bp)
Default Constructor
Parameters
bp BorderPane to add the Tabs to
Definition at line 36 of file WorkspaceTabsController.java.
References view.controllers.WorkspaceTabsController.makeActive(), and view.controllers.WorkspaceTabsController.newTab().
Member Function Documentation
void view.controllers.WorkspaceTabsController.makeActive (Tab t1) private
Makes a tab active
Parameters
t1 Tab that is to be active
Definition at line 76 of file WorkspaceTabsController.java.
References view.controllers.PaneController.populate().
Referenced by view.controllers.WorkspaceTabsController.newTab(), and view.controllers.WorkspaceTabsController.WorkspaceTabsController().
void view.controllers.WorkspaceTabsController.newTab () private
Makes a new Tab and new Workspace
Definition at line 60 of file WorkspaceTabsController.java.
References view.controllers.WorkspaceTabsController.makeActive().
Referenced by view.controllers.WorkspaceTabsController.WorkspaceTabsController().
Member Data Documentation
BorderPane view.controllers.WorkspaceTabsController.myBorderPane private
Definition at line 27 of file WorkspaceTabsController.java.
HBox view.controllers.WorkspaceTabsController.myHbox = new HBox() private
Definition at line 24 of file WorkspaceTabsController.java.
TabPane view.controllers.WorkspaceTabsController.myTabPane = new TabPane() private
Definition at line 25 of file WorkspaceTabsController.java.
VBox view.controllers.WorkspaceTabsController.myVBox = new VBox() private
Definition at line 28 of file WorkspaceTabsController.java.
List<PaneController> view.controllers.WorkspaceTabsController.myWorkspaces = new ArrayList<PaneController>() private
Definition at line 26 of file WorkspaceTabsController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/controllers/WorkspaceTabsController.java