slogo_team14: view.controllers.PaneController Class Reference
view.controllers.PaneController Class Reference
Public Member Functions
PaneController (BorderPane bp, VBox v)
void populate (BorderPane bp)
void showError (String s)
void update (Observable obs, Object arg1)
Private Attributes
List< PaneModule > myPanes = new ArrayList<PaneModule>()
CommandString myCommand = new CommandString(this)
ImagePalette myImagePalette = new ImagePalette()
ViewPaneModule myView = new ViewPaneModule(myImagePalette)
Controller myController = new Controller(myView, this)
MasterController myMasterController = new MasterController("English")
LanguageController myLanguageController = new LanguageController(myMasterController)
Detailed Description
Contains all Panes populating the User Interface. Builds the User Interface with the Panes. Provides an interface between the Panes as well as between the Panes and the Model Controller.
Author
Team 14
Definition at line 29 of file PaneController.java.
Constructor & Destructor Documentation
view.controllers.PaneController.PaneController (BorderPane bp, VBox v)
Constructor. Adds Panes to myPanes.
Definition at line 47 of file PaneController.java.
References view.controllers.PaneController.populate().
Member Function Documentation
void view.controllers.PaneController.populate (BorderPane bp)
Iterates through all Panes in myPanes and properly adds them to and configures them in the BorderPane to be displayed in the User Interface.
Parameters
bp BorderPane that the Panes are to be added to.
Returns
BorderPane with Panes configured and populated.
Definition at line 64 of file PaneController.java.
Referenced by view.controllers.WorkspaceTabsController.makeActive(), and view.controllers.PaneController.PaneController().
void view.controllers.PaneController.showError (String s)
Shows an error from the backend
Parameters
s String representing an error
Definition at line 76 of file PaneController.java.
References view.Constants.ERROR, and view.CommandString.setCommand().
Referenced by controller.Controller.getInput().
void view.controllers.PaneController.update (Observable obs, Object arg1)
When the CommandString changes (a new command has been input), the update method sends the command to be parsed by the backend.
Definition at line 85 of file PaneController.java.
References view.Constants.ERROR, view.CommandString.getCommand(), controller.Controller.getInput(), view.CommandString.getType(), and view.Constants.USER_DEFINE.
Member Data Documentation
CommandString view.controllers.PaneController.myCommand = new CommandString(this) private
CommandString containing the current command to be passed to the backend.
Definition at line 37 of file PaneController.java.
Controller view.controllers.PaneController.myController = new Controller(myView, this) private
Definition at line 40 of file PaneController.java.
ImagePalette view.controllers.PaneController.myImagePalette = new ImagePalette() private
Definition at line 38 of file PaneController.java.
LanguageController view.controllers.PaneController.myLanguageController = new LanguageController(myMasterController) private
Definition at line 42 of file PaneController.java.
MasterController view.controllers.PaneController.myMasterController = new MasterController("English") private
Definition at line 41 of file PaneController.java.
List<PaneModule> view.controllers.PaneController.myPanes = new ArrayList<PaneModule>() private
Contains all Panes in the User Interface
Definition at line 33 of file PaneController.java.
ViewPaneModule view.controllers.PaneController.myView = new ViewPaneModule(myImagePalette) private
Definition at line 39 of file PaneController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/controllers/PaneController.java