slogo_team14: view.controllers.LanguageController Class Reference
view.controllers.LanguageController Class Reference
Public Member Functions
LanguageController (MasterController mc)
void setLanguage (String s)
ChoiceBox< String > makeMenu ()
Static Public Attributes
static final String DEFAULT_LANGUAGE = "English"
Private Attributes
MasterController myMasterController
Static Private Attributes
static final String[] LANGUAGE
Detailed Description
Allows selection of various command language translations
Author
Team 14
Definition at line 15 of file LanguageController.java.
Constructor & Destructor Documentation
view.controllers.LanguageController.LanguageController (MasterController mc)
Default Constructor
Parameters
mc MasterController for the program
Definition at line 27 of file LanguageController.java.
Member Function Documentation
ChoiceBox<String> view.controllers.LanguageController.makeMenu ()
Makes a ChoiceBox of the possible language options
Returns
ChoiceBox of the possible language options
Definition at line 46 of file LanguageController.java.
References view.controllers.LanguageController.setLanguage().
Referenced by view.panes.ButtonPaneModule.createPropertiesMenu().
void view.controllers.LanguageController.setLanguage (String s)
Set the language of the Master Controller
Parameters
s String representing the language for translation
Definition at line 37 of file LanguageController.java.
References controller.MasterController.constructMasterController().
Referenced by view.controllers.LanguageController.makeMenu().
Member Data Documentation
final String view.controllers.LanguageController.DEFAULT_LANGUAGE = "English" static
Definition at line 16 of file LanguageController.java.
final String [] view.controllers.LanguageController.LANGUAGE static private
Initial value:
= new String[] { "English", "Chinese", "French",
            "Italian", "Portuguese", "Russian" }
Definition at line 17 of file LanguageController.java.
MasterController view.controllers.LanguageController.myMasterController private
Definition at line 19 of file LanguageController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/controllers/LanguageController.java