slogo_team14: view.panes.HistoryPaneModule Class Reference
view.panes.HistoryPaneModule Class Reference
Public Member Functions
HistoryPaneModule (CommandString cs)
void addItem (String s)
BorderPane addPane (BorderPane p)
void update (java.util.Observable o, Object arg)
Public Member Functions inherited from view.panes.PaneModule
abstract BorderPane addPane (BorderPane p)
Private Attributes
VBox myRoot = new VBox()
ScrollPane myHistoryScroll = new ScrollPane()
ScrollPane mySavedScroll = new ScrollPane()
VBox myHistoryDisplay = new VBox()
VBox mySavedDisplay = new VBox()
CommandString myCommandString
Detailed Description
Subclass of Pane that implements a scrollable Vbox which is populated with hyperlinks of commands as they are input. Allows old commands to be clicked on to be resubmitted
Author
Team 14
Definition at line 23 of file HistoryPaneModule.java.
Constructor & Destructor Documentation
view.panes.HistoryPaneModule.HistoryPaneModule (CommandString cs)
Definition at line 32 of file HistoryPaneModule.java.
Member Function Documentation
void view.panes.HistoryPaneModule.addItem (String s)
Adds a new Item. Can either be a history command, error message, or user defined saved command
Parameters
s String representing command
Definition at line 51 of file HistoryPaneModule.java.
References view.Constants.COMMAND, view.Constants.ERROR, view.CommandString.getCommand(), view.CommandString.getType(), view.CommandString.setCommand(), and view.Constants.USER_DEFINE.
Referenced by view.panes.HistoryPaneModule.update().
BorderPane view.panes.HistoryPaneModule.addPane (BorderPane p)
Adds pane to BorderPane
Definition at line 78 of file HistoryPaneModule.java.
void view.panes.HistoryPaneModule.update (java.util.Observable o, Object arg)
Observable to update History when a Command is entered
Definition at line 87 of file HistoryPaneModule.java.
References view.panes.HistoryPaneModule.addItem(), and view.CommandString.getCommand().
Member Data Documentation
CommandString view.panes.HistoryPaneModule.myCommandString private
Definition at line 30 of file HistoryPaneModule.java.
VBox view.panes.HistoryPaneModule.myHistoryDisplay = new VBox() private
Definition at line 28 of file HistoryPaneModule.java.
ScrollPane view.panes.HistoryPaneModule.myHistoryScroll = new ScrollPane() private
Definition at line 26 of file HistoryPaneModule.java.
VBox view.panes.HistoryPaneModule.myRoot = new VBox() private
Definition at line 25 of file HistoryPaneModule.java.
VBox view.panes.HistoryPaneModule.mySavedDisplay = new VBox() private
Definition at line 29 of file HistoryPaneModule.java.
ScrollPane view.panes.HistoryPaneModule.mySavedScroll = new ScrollPane() private
Definition at line 27 of file HistoryPaneModule.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/panes/HistoryPaneModule.java