slogo_team14: view.TurtleDraw Class Reference
view.TurtleDraw Class Reference
Public Member Functions
TurtleDraw (ImagePalette ip)
ImageView drawTurtle (Turtle t, boolean b)
void drawLine (Point2D cur, Point2D next)
void moveTurtle (ImageView figure, Point2D next)
void setAngle (ImageView figure, double angle)
void showTurtle (Pane p, ImageView figure)
void hideTurtle (Pane p, ImageView figure)
Public Attributes
Line myPath
File myImage
Color myLineColor
Private Attributes
ImagePalette myImagePalette
Detailed Description
Handles the drawing of the simulation. Draws and moves turtles accordingly. Draws lines accorrdingly.
Author
Team 14
Definition at line 24 of file TurtleDraw.java.
Constructor & Destructor Documentation
view.TurtleDraw.TurtleDraw (ImagePalette ip)
Constructor for TurtleDraw
Parameters
ip ImagePalette containing the turtle images
Definition at line 37 of file TurtleDraw.java.
Member Function Documentation
void view.TurtleDraw.drawLine (Point2D cur, Point2D next)
Draws a line between two points
Parameters
cur Point2D representing Current Point
next Point2D representing Next Point
Definition at line 85 of file TurtleDraw.java.
References view.Constants.VIEW_DEFAULT_DIMENSION.
Referenced by view.panes.ViewPaneModule.updateTurtle().
ImageView view.TurtleDraw.drawTurtle (Turtle t, boolean b)
Draws a new turtle
Parameters
t Turtle to be drawn to the front end
b True is turtle is to be highlighted as active
Returns
ImageView representing drawn turtle
Definition at line 50 of file TurtleDraw.java.
References view.controllers.ImagePalette.getImage(), model.Turtle.getShape(), view.Constants.IMAGE_HEIGHT, view.Constants.IMAGE_WIDTH, and view.Constants.VIEW_DEFAULT_DIMENSION.
Referenced by view.panes.ViewPaneModule.makeStamps(), and view.panes.ViewPaneModule.updateTurtle().
void view.TurtleDraw.hideTurtle (Pane p, ImageView figure)
Hides a given turtle
Parameters
p Pane showing simulation
figure ImageView representing a given turtle
Definition at line 142 of file TurtleDraw.java.
Referenced by view.panes.ViewPaneModule.eraseStamps(), and view.panes.ViewPaneModule.updateTurtle().
void view.TurtleDraw.moveTurtle (ImageView figure, Point2D next)
Moves the ImageView representing a given turtle
Parameters
figure ImageView representing a given turtle
next Point2D representing Next Point
Definition at line 102 of file TurtleDraw.java.
References view.Constants.IMAGE_HEIGHT, view.Constants.IMAGE_WIDTH, and view.Constants.VIEW_DEFAULT_DIMENSION.
Referenced by view.panes.ViewPaneModule.makeStamps(), and view.panes.ViewPaneModule.updateTurtle().
void view.TurtleDraw.setAngle (ImageView figure, double angle)
Rotates the ImageView to a given angle
Parameters
figure ImageView to be rotated
angle Double representing angle to be rotated to
Definition at line 118 of file TurtleDraw.java.
Referenced by view.panes.ViewPaneModule.makeStamps(), and view.panes.ViewPaneModule.updateTurtle().
void view.TurtleDraw.showTurtle (Pane p, ImageView figure)
Shows a given turtle
Parameters
p Pane showing simulation
figure ImageView representing a given turtle
Definition at line 130 of file TurtleDraw.java.
Referenced by view.panes.ViewPaneModule.makeStamps(), and view.panes.ViewPaneModule.updateTurtle().
Member Data Documentation
File view.TurtleDraw.myImage
Definition at line 27 of file TurtleDraw.java.
ImagePalette view.TurtleDraw.myImagePalette private
Definition at line 28 of file TurtleDraw.java.
Color view.TurtleDraw.myLineColor
Definition at line 29 of file TurtleDraw.java.
Line view.TurtleDraw.myPath
Definition at line 26 of file TurtleDraw.java.
Referenced by view.panes.ViewPaneModule.updateTurtle().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/TurtleDraw.java