slogo_team14: controller.MasterController Class Reference
controller.MasterController Class Reference
Public Member Functions
MasterController (String lang)
void constructMasterController (String lang)
Static Public Attributes
static Parser myParser
static Random myRandom = new Random()
Private Member Functions
Set< String > constructSet ()
Private Attributes
final String myResources = "resources.languages/"
Detailed Description
Class to contain the Parser and a set of executable commands. This information is used by Controller subclasses.
Author
Team 14
Definition at line 19 of file MasterController.java.
Constructor & Destructor Documentation
controller.MasterController.MasterController (String lang)
Definition at line 25 of file MasterController.java.
References controller.MasterController.constructMasterController().
Member Function Documentation
void controller.MasterController.constructMasterController (String lang)
Definition at line 30 of file MasterController.java.
References controller.MasterController.constructSet(), and parser.Parser.resetParser().
Referenced by controller.MasterController.MasterController(), and view.controllers.LanguageController.setLanguage().
Set<String> controller.MasterController.constructSet () private
Definition at line 53 of file MasterController.java.
Referenced by controller.MasterController.constructMasterController().
Member Data Documentation
Parser controller.MasterController.myParser static
Definition at line 21 of file MasterController.java.
Referenced by commands.MakeUserInstructionCommand.executeCommand(), and controller.Controller.getInput().
Random controller.MasterController.myRandom = new Random() static
Definition at line 22 of file MasterController.java.
Referenced by commands.RandomCommand.executeCommand().
final String controller.MasterController.myResources = "resources.languages/" private
Definition at line 23 of file MasterController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/controller/MasterController.java