slogo_team14: view.CommandString Class Reference
view.CommandString Class Reference
Public Member Functions
CommandString (Observer o)
void setCommand (String s, int t)
String getCommand ()
int getType ()
Private Attributes
String myCommand
int myType
Detailed Description
Contains an Observable String that represents the current command being passed into the Front End. Allows Observers to detect that a new command has been input and make the appropriate method calls in response to the command input.
Author
Team 14
Definition at line 15 of file CommandString.java.
Constructor & Destructor Documentation
view.CommandString.CommandString (Observer o)
Constructor that adds an observer
Parameters
o Observer to be added to CommandString
Definition at line 29 of file CommandString.java.
Member Function Documentation
String view.CommandString.getCommand ()
Getter to get the current command
Returns
String containing the current command
Definition at line 54 of file CommandString.java.
References view.CommandString.myCommand.
Referenced by view.panes.HistoryPaneModule.addItem(), view.controllers.PaneController.update(), and view.panes.HistoryPaneModule.update().
int view.CommandString.getType ()
Getter to get the type of command contained within the CommandString
Returns
int representing the type of command
Definition at line 63 of file CommandString.java.
References view.CommandString.myType.
Referenced by view.panes.HistoryPaneModule.addItem(), and view.controllers.PaneController.update().
void view.CommandString.setCommand (String s, int t)
Setter to set the current command
Parameters
s String representing the current command
t int representing the type of command
Definition at line 42 of file CommandString.java.
Referenced by view.panes.HistoryPaneModule.addItem(), view.panes.TurtleControllerPaneModule.angle(), view.panes.ButtonPaneModule.backgroundColor(), view.panes.PenPane.changePenColor(), view.panes.TurtleControllerPaneModule.makeTurtle(), view.panes.TurtleControllerPaneModule.move(), view.panes.PenPane.PenPane(), view.panes.InputPaneModule.save(), view.panes.PenPane.setPenDash(), view.panes.PenPane.setPenStyle(), view.panes.PenPane.setPenWidth(), view.controllers.PaneController.showError(), view.panes.InputPaneModule.submit(), and view.panes.TurtleSelectorPane.toggleActiveTurtles().
Member Data Documentation
String view.CommandString.myCommand private
String containing the current command
Definition at line 20 of file CommandString.java.
Referenced by view.CommandString.getCommand().
int view.CommandString.myType private
Definition at line 21 of file CommandString.java.
Referenced by view.CommandString.getType().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/CommandString.java