slogo_team14: model.Model Class Reference
model.Model Class Reference
Public Member Functions
Model (ViewPaneModule view)
void updateModel (Collection< Command > commandsToExecute)
void notifyView ()
ViewPaneModule getView ()
TurtleSetManager getTurtleManager ()
VariableManager getVariableManager ()
double setBackgroundColor (double red, double green, double blue)
Color getBackgroundColor ()
double getStamp ()
double setStamp (double stamp)
Private Attributes
ViewPaneModule myView
Color myBackground
Set< Turtle > myFullSet
TurtleSetManager myTurtleManager
VariableManager myVariableManager
double isStamp
Detailed Description
Class that contains the basic information of what needs to be displayed in the GUI, including data related to the turtle (current position, pen color, pen up/down). The Model is always updated before the ViewPanel is updated.
Author
Team 14
Definition at line 17 of file Model.java.
Constructor & Destructor Documentation
model.Model.Model (ViewPaneModule view)
Constructor method called from ViewPanel.java
Parameters
view : The ViewPanel that called this constructor.
Definition at line 32 of file Model.java.
Member Function Documentation
Color model.Model.getBackgroundColor ()
Method to return the background color to the view.
Definition at line 103 of file Model.java.
References model.Model.myBackground.
Referenced by view.panes.ViewPaneModule.updateView().
double model.Model.getStamp ()
Method to tell the view if the active turtles should stamp or not
Definition at line 109 of file Model.java.
References model.Model.isStamp.
Referenced by view.panes.ViewPaneModule.updateView().
TurtleSetManager model.Model.getTurtleManager ()
Method to return the manager that holds the collections of active turtles and the full list of turtles to the front end
Definition at line 72 of file Model.java.
References model.Model.myTurtleManager.
Referenced by commands.AskCommand.executeCommand(), commands.AskWithCommand.executeCommand(), commands.TellCommand.executeCommand(), commands.Command.executeCommand(), commands.Command.getFirstTurtle(), and view.panes.ViewPaneModule.updateView().
VariableManager model.Model.getVariableManager ()
Method to return the manager that holds the collections of variables, both global and local
Definition at line 80 of file Model.java.
References model.Model.myVariableManager.
Referenced by commands.MakeVariableCommand.executeCommand(), commands.DoTimesCommand.executeCommand(), commands.ForCommand.executeCommand(), commands.CustomCommand.executeCommand(), and commands.VariableCommand.executeCommand().
ViewPaneModule model.Model.getView ()
Method to return the view (as a viewpanemodule) after it's updatedd.
Definition at line 64 of file Model.java.
References model.Model.myView.
void model.Model.notifyView ()
Method to notify the view when things change in the model
Definition at line 57 of file Model.java.
References view.panes.ViewPaneModule.updateView().
Referenced by commands.Command.executeCommand(), and model.Model.updateModel().
double model.Model.setBackgroundColor (double red, double green, double blue)
Method to update the background color
Parameters
red : how much red blue: how much blue green: how much green
Definition at line 91 of file Model.java.
Referenced by commands.SetBackgroundCommand.executeCommand().
double model.Model.setStamp (double stamp)
Method to change whether or not active turtles stamp.
Definition at line 115 of file Model.java.
Referenced by commands.StampCommand.executeCommand(), commands.ClearStampsCommand.executeCommand(), and view.panes.ViewPaneModule.updateView().
void model.Model.updateModel (Collection< Command > commandsToExecute)
Method to update the model with the commands passed from the Controller.
Parameters
commandsToExecute : Collection of commands to execute.
Definition at line 47 of file Model.java.
References model.Model.notifyView().
Referenced by controller.Controller.runCommand().
Member Data Documentation
double model.Model.isStamp private
Definition at line 24 of file Model.java.
Referenced by model.Model.getStamp().
Color model.Model.myBackground private
Definition at line 20 of file Model.java.
Referenced by model.Model.getBackgroundColor().
Set<Turtle> model.Model.myFullSet private
Definition at line 21 of file Model.java.
TurtleSetManager model.Model.myTurtleManager private
Definition at line 22 of file Model.java.
Referenced by model.Model.getTurtleManager().
VariableManager model.Model.myVariableManager private
Definition at line 23 of file Model.java.
Referenced by model.Model.getVariableManager().
ViewPaneModule model.Model.myView private
Definition at line 19 of file Model.java.
Referenced by model.Model.getView().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/model/Model.java