slogo_team14: controller.Controller Class Reference
controller.Controller Class Reference
Public Member Functions
Controller (ViewPaneModule view, PaneController pane)
void getInput (String input)
Package Attributes
ViewPaneModule myView
Model myModel
Private Member Functions
void runCommand (List< Command > commandsToExecute)
Private Attributes
PaneController myPane
Detailed Description
Communicates between the View, the Parser, and the Model. The Controller accepts a string from the ViewPanel, uses the Parser to parse it into a collection of commands, and either returns an ErrorCommand to the ViewPanel (if an error is detected) or runs the commands through the Model.
Author
Team 14
Definition at line 20 of file Controller.java.
Constructor & Destructor Documentation
controller.Controller.Controller (ViewPaneModule view, PaneController pane)
Constructor method called from ViewPanel.java
Parameters
view : The ViewPanel that called this constructor.
model : The Model constructed by said ViewPanel.
Definition at line 34 of file Controller.java.
Member Function Documentation
void controller.Controller.getInput (String input)
Accepts a string from the ViewPanel, parses it using a static parser in the MasterController class, and searches the returned collection of commands for errors. If an error is found, it is displayed in the view, and no commands are executed. Otherwise, all commands are run in sequence.
Parameters
input : User input string from the ViewPanel.
Definition at line 50 of file Controller.java.
References controller.MasterController.myParser, parser.Parser.parseInput(), controller.Controller.runCommand(), commands.ErrorCommand.showError(), and view.controllers.PaneController.showError().
Referenced by view.controllers.PaneController.update().
void controller.Controller.runCommand (List< Command > commandsToExecute) private
Passes the commands to the Model to execute.
Parameters
commandsToExecute : The commands to execute.
Definition at line 67 of file Controller.java.
References model.Model.updateModel().
Referenced by controller.Controller.getInput().
Member Data Documentation
Model controller.Controller.myModel package
Definition at line 23 of file Controller.java.
PaneController controller.Controller.myPane private
Definition at line 24 of file Controller.java.
ViewPaneModule controller.Controller.myView package
Definition at line 22 of file Controller.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/controller/Controller.java