slogo_team14: view.panes.TurtleSelectorPane Class Reference
view.panes.TurtleSelectorPane Class Reference
Public Member Functions
TurtleSelectorPane (CommandString cs, ViewPaneModule vp)
void newTurtle (int id)
void getActiveTurtles ()
void toggleActiveTurtles ()
ScrollPane getPane ()
Private Attributes
Set< Integer > myTurtles = new HashSet<Integer>()
Set< CheckBox > myBoxes = new HashSet<CheckBox>()
Map< CheckBox, Integer > myIDs = new HashMap<CheckBox, Integer>()
Set< Integer > myActiveTurtles = new HashSet<Integer>()
CommandString myCommandString
CheckBox myToggle = new CheckBox("Toggle Identification")
ScrollPane myTurtleScroll = new ScrollPane()
VBox myVBox = new VBox()
ViewPaneModule myViewPane
Detailed Description
Allows for graphical toggling of active turtles
Author
Team 14
Definition at line 23 of file TurtleSelectorPane.java.
Constructor & Destructor Documentation
view.panes.TurtleSelectorPane.TurtleSelectorPane (CommandString cs, ViewPaneModule vp)
Definition at line 34 of file TurtleSelectorPane.java.
References view.panes.ViewPaneModule.toggleActive().
Member Function Documentation
void view.panes.TurtleSelectorPane.getActiveTurtles ()
Gets all turtles set to be active by the user
Definition at line 81 of file TurtleSelectorPane.java.
References view.panes.TurtleSelectorPane.toggleActiveTurtles().
Referenced by view.panes.TurtleSelectorPane.newTurtle().
ScrollPane view.panes.TurtleSelectorPane.getPane ()
Gets the Pane
Returns
ScrollPane containing the TurtleSelector
Definition at line 109 of file TurtleSelectorPane.java.
References view.panes.TurtleSelectorPane.myTurtleScroll.
Referenced by view.panes.TurtleControllerPaneModule.TurtleControllerPaneModule().
void view.panes.TurtleSelectorPane.newTurtle (int id)
Makes a new Turtle toggle for a new turtle made by the GUI
Parameters
id ID of the new Turtle
Definition at line 55 of file TurtleSelectorPane.java.
References view.panes.TurtleSelectorPane.getActiveTurtles().
Referenced by view.panes.TurtleControllerPaneModule.makeTurtle().
void view.panes.TurtleSelectorPane.toggleActiveTurtles ()
Sets the active turtles to be active for command input
Definition at line 95 of file TurtleSelectorPane.java.
References view.CommandString.setCommand(), and view.Constants.SETTING.
Referenced by view.panes.TurtleSelectorPane.getActiveTurtles().
Member Data Documentation
Set<Integer> view.panes.TurtleSelectorPane.myActiveTurtles = new HashSet<Integer>() private
Definition at line 27 of file TurtleSelectorPane.java.
Set<CheckBox> view.panes.TurtleSelectorPane.myBoxes = new HashSet<CheckBox>() private
Definition at line 25 of file TurtleSelectorPane.java.
CommandString view.panes.TurtleSelectorPane.myCommandString private
Definition at line 28 of file TurtleSelectorPane.java.
Map<CheckBox, Integer> view.panes.TurtleSelectorPane.myIDs = new HashMap<CheckBox, Integer>() private
Definition at line 26 of file TurtleSelectorPane.java.
CheckBox view.panes.TurtleSelectorPane.myToggle = new CheckBox("Toggle Identification") private
Definition at line 29 of file TurtleSelectorPane.java.
Set<Integer> view.panes.TurtleSelectorPane.myTurtles = new HashSet<Integer>() private
Definition at line 24 of file TurtleSelectorPane.java.
ScrollPane view.panes.TurtleSelectorPane.myTurtleScroll = new ScrollPane() private
Definition at line 30 of file TurtleSelectorPane.java.
Referenced by view.panes.TurtleSelectorPane.getPane().
VBox view.panes.TurtleSelectorPane.myVBox = new VBox() private
Definition at line 31 of file TurtleSelectorPane.java.
ViewPaneModule view.panes.TurtleSelectorPane.myViewPane private
Definition at line 32 of file TurtleSelectorPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/panes/TurtleSelectorPane.java