slogo_team14: view.controllers.WorkspacePropertiesController Class Reference
view.controllers.WorkspacePropertiesController Class Reference
Public Member Functions
WorkspacePropertiesController ()
void saveWorkspace ()
Private Member Functions
Button makeButton (String property, EventHandler< ActionEvent > handler)
Detailed Description
Allows the saving and loading of the properties within a workspace. Not fully implemented and not used.
Author
Team 14
Definition at line 22 of file WorkspacePropertiesController.java.
Constructor & Destructor Documentation
view.controllers.WorkspacePropertiesController.WorkspacePropertiesController ()
Definition at line 23 of file WorkspacePropertiesController.java.
References view.controllers.WorkspacePropertiesController.makeButton(), and view.controllers.WorkspacePropertiesController.saveWorkspace().
Member Function Documentation
Button view.controllers.WorkspacePropertiesController.makeButton (String property, EventHandler< ActionEvent > handler) private
Definition at line 27 of file WorkspacePropertiesController.java.
Referenced by view.controllers.WorkspacePropertiesController.WorkspacePropertiesController().
void view.controllers.WorkspacePropertiesController.saveWorkspace ()
Definition at line 35 of file WorkspacePropertiesController.java.
Referenced by view.controllers.WorkspacePropertiesController.WorkspacePropertiesController().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/controllers/WorkspacePropertiesController.java