slogo_team14: view.panes.TurtleControllerPaneModule Class Reference
view.panes.TurtleControllerPaneModule Class Reference
Classes
class MoveHandler
Public Member Functions
TurtleControllerPaneModule (CommandString cs, ImagePalette ip, ViewPaneModule vp)
BorderPane addPane (BorderPane p)
Public Member Functions inherited from view.panes.PaneModule
abstract BorderPane addPane (BorderPane p)
Private Member Functions
HBox imageSelectorMaker ()
Button makeButton (String property, EventHandler< ActionEvent > handler)
void doChoose ()
void move ()
void angle ()
void makeTurtle ()
void move (int orientation)
Private Attributes
VBox myVbox = new VBox()
TextField myMoveTextField = new TextField()
TextField myAngleTextField = new TextField()
TextField myIDTextField = new TextField("0")
CommandString myCommandString
TurtleSelectorPane myTurtles
Set< Integer > myActiveTurtles = new HashSet<Integer>()
Map< Integer, String > myImages = new HashMap<Integer, String>()
ImagePalette myImagePalette
HBox myImageBar = new HBox()
PenPane myPenPane
Detailed Description
Allows the GUI control over turtles
Author
Team 14
Definition at line 31 of file TurtleControllerPaneModule.java.
Constructor & Destructor Documentation
view.panes.TurtleControllerPaneModule.TurtleControllerPaneModule (CommandString cs, ImagePalette ip, ViewPaneModule vp)
Initializes the parameters of the InputPane.
Parameters
cs CommandString containing the String that represents the current command
Definition at line 51 of file TurtleControllerPaneModule.java.
References view.panes.TurtleControllerPaneModule.angle(), view.panes.TurtleSelectorPane.getPane(), view.panes.PenPane.getPenPane(), view.panes.TurtleControllerPaneModule.imageSelectorMaker(), view.panes.TurtleControllerPaneModule.makeButton(), view.panes.TurtleControllerPaneModule.makeTurtle(), and view.panes.TurtleControllerPaneModule.move().
Member Function Documentation
BorderPane view.panes.TurtleControllerPaneModule.addPane (BorderPane p)
Adds the pane to the BorderPane
Definition at line 145 of file TurtleControllerPaneModule.java.
void view.panes.TurtleControllerPaneModule.angle () private
Sets the Orientation of the turtle using the GUI
Definition at line 134 of file TurtleControllerPaneModule.java.
References view.CommandString.setCommand(), and view.Constants.SETTING.
Referenced by view.panes.TurtleControllerPaneModule.TurtleControllerPaneModule().
void view.panes.TurtleControllerPaneModule.doChoose () private
Defines the behavior for when a File Chooser is used to select a new image to be added to the Image Palette
Definition at line 107 of file TurtleControllerPaneModule.java.
References view.controllers.ImagePalette.addImage().
Referenced by view.panes.TurtleControllerPaneModule.imageSelectorMaker().
HBox view.panes.TurtleControllerPaneModule.imageSelectorMaker () private
Makes a new ImageSelector System
Returns
HBox containing image selector items
Definition at line 80 of file TurtleControllerPaneModule.java.
References view.panes.TurtleControllerPaneModule.doChoose(), view.controllers.ImagePalette.getBox(), view.panes.TurtleControllerPaneModule.makeButton(), and view.panes.TurtleControllerPaneModule.myImageBar.
Referenced by view.panes.TurtleControllerPaneModule.TurtleControllerPaneModule().
Button view.panes.TurtleControllerPaneModule.makeButton (String property, EventHandler< ActionEvent > handler) private
Button Factory
Parameters
property String label for button
handler EventHandler for the button
Returns
Completed Button
Definition at line 95 of file TurtleControllerPaneModule.java.
Referenced by view.panes.TurtleControllerPaneModule.imageSelectorMaker(), and view.panes.TurtleControllerPaneModule.TurtleControllerPaneModule().
void view.panes.TurtleControllerPaneModule.makeTurtle () private
Makes a new turtle with a user defined ID number and turtle image using the GUI
Definition at line 154 of file TurtleControllerPaneModule.java.
References view.controllers.ImagePalette.getCurrentImageID(), view.panes.TurtleSelectorPane.newTurtle(), view.panes.PenPane.newTurtle(), view.CommandString.setCommand(), and view.Constants.SETTING.
Referenced by view.panes.TurtleControllerPaneModule.TurtleControllerPaneModule().
void view.panes.TurtleControllerPaneModule.move () private
Moves the turtle using the GUI
Definition at line 124 of file TurtleControllerPaneModule.java.
References view.CommandString.setCommand(), and view.Constants.SETTING.
Referenced by view.panes.TurtleControllerPaneModule.MoveHandler.handle(), and view.panes.TurtleControllerPaneModule.TurtleControllerPaneModule().
void view.panes.TurtleControllerPaneModule.move (int orientation) private
Works with the MoveHandler to move a turtle using the WASD keys
Parameters
orientation Int representing the direction of movement
Definition at line 172 of file TurtleControllerPaneModule.java.
References view.CommandString.setCommand().
Member Data Documentation
Set<Integer> view.panes.TurtleControllerPaneModule.myActiveTurtles = new HashSet<Integer>() private
Definition at line 38 of file TurtleControllerPaneModule.java.
TextField view.panes.TurtleControllerPaneModule.myAngleTextField = new TextField() private
Definition at line 34 of file TurtleControllerPaneModule.java.
CommandString view.panes.TurtleControllerPaneModule.myCommandString private
Definition at line 36 of file TurtleControllerPaneModule.java.
TextField view.panes.TurtleControllerPaneModule.myIDTextField = new TextField("0") private
Definition at line 35 of file TurtleControllerPaneModule.java.
HBox view.panes.TurtleControllerPaneModule.myImageBar = new HBox() private
Definition at line 41 of file TurtleControllerPaneModule.java.
Referenced by view.panes.TurtleControllerPaneModule.imageSelectorMaker().
ImagePalette view.panes.TurtleControllerPaneModule.myImagePalette private
Definition at line 40 of file TurtleControllerPaneModule.java.
Map<Integer, String> view.panes.TurtleControllerPaneModule.myImages = new HashMap<Integer, String>() private
Definition at line 39 of file TurtleControllerPaneModule.java.
TextField view.panes.TurtleControllerPaneModule.myMoveTextField = new TextField() private
Definition at line 33 of file TurtleControllerPaneModule.java.
PenPane view.panes.TurtleControllerPaneModule.myPenPane private
Definition at line 42 of file TurtleControllerPaneModule.java.
TurtleSelectorPane view.panes.TurtleControllerPaneModule.myTurtles private
Definition at line 37 of file TurtleControllerPaneModule.java.
VBox view.panes.TurtleControllerPaneModule.myVbox = new VBox() private
Definition at line 32 of file TurtleControllerPaneModule.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/panes/TurtleControllerPaneModule.java