slogo_team14: parser.Parser Class Reference
parser.Parser Class Reference
Public Member Functions
void resetParser (Map< String, String > commandMap, Map< String, String > regularExpressions)
void addUserInputCommand (String name, CustomCommand command)
Stack< Command > parseInput (String parseInput)
Private Member Functions
Command getCommand (String commandName, Stack< Command > parameterStack)
Command makeListCommand (Stack< String > commandStack)
Stack< Command > throwError (String errorMessage)
Private Attributes
Stack< String > myCommandStack = new Stack<String>()
Map< String, String > myCommandMap
Map< String, String > myRegularExpressions
Map< String, CustomCommand > myUserInputCommands
Static Private Attributes
static String EMPTY_SPACE = ""
Detailed Description
This class is used to convert a string to a collection of commands to execute.
Author
Team 14
Definition at line 21 of file Parser.java.
Member Function Documentation
void parser.Parser.addUserInputCommand (String name, CustomCommand command)
Definition at line 35 of file Parser.java.
Referenced by commands.MakeUserInstructionCommand.executeCommand().
Command parser.Parser.getCommand (String commandName, Stack< Command > parameterStack) private
This method gets a string of command name and, using reflection, returns command object or error, if it doesn't exist.
Parameters
commandName - a string of command name
parameterStack - stack of commands that contains parameters
Returns
either command or error
Definition at line 89 of file Parser.java.
References commands.Command.getNumParameters(), parser.Parser.makeListCommand(), and commands.Command.setParameters().
Referenced by parser.Parser.makeListCommand(), and parser.Parser.parseInput().
Command parser.Parser.makeListCommand (Stack< String > commandStack) private
When encountering "]", this method is used to create a ListCommand
Parameters
commandStack
Returns
ListCommand
Definition at line 139 of file Parser.java.
References parser.Parser.getCommand().
Referenced by parser.Parser.getCommand().
Stack<Command> parser.Parser.parseInput (String parseInput)
Parses a string input and constructs a collection of executable commands.
Parameters
input : String to parse.
Returns
Collection of commands to execute.
Definition at line 47 of file Parser.java.
References commands.Command.getClassName(), parser.Parser.getCommand(), and parser.Parser.throwError().
Referenced by controller.Controller.getInput().
void parser.Parser.resetParser (Map< String, String > commandMap, Map< String, String > regularExpressions)
Definition at line 29 of file Parser.java.
Referenced by controller.MasterController.constructMasterController().
Stack<Command> parser.Parser.throwError (String errorMessage) private
Definition at line 158 of file Parser.java.
Referenced by parser.Parser.parseInput().
Member Data Documentation
String parser.Parser.EMPTY_SPACE = "" static private
Definition at line 23 of file Parser.java.
Map<String, String> parser.Parser.myCommandMap private
Definition at line 25 of file Parser.java.
Stack<String> parser.Parser.myCommandStack = new Stack<String>() private
Definition at line 24 of file Parser.java.
Map<String, String> parser.Parser.myRegularExpressions private
Definition at line 26 of file Parser.java.
Map<String, CustomCommand> parser.Parser.myUserInputCommands private
Definition at line 27 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/parser/Parser.java