slogo_team14: model.Turtle Class Reference
model.Turtle Class Reference
Public Member Functions
Turtle (double identification)
int compareTo (Object obj)
double updatePosition (double forward)
void getmyCurr ()
double setPenSize (double size)
double setPenDash (double dash)
double updateHeading (double degree)
double getHeading ()
double setHeading (double degree)
double towards (double x, double y)
double setXAndY (double x, double y)
double changePen (double pen)
double setPenColor (double red, double green, double blue)
double changeVisibility (double visible)
Point2D getNewLocation ()
Point2D getPrevLocation ()
double getPenStatus ()
double getPenSize ()
double getPenDash ()
double getShowing ()
double setShape (double shapeID)
double getShape ()
Color getPenColor ()
double getID ()
void setPenStatus (double d)
Map getStats ()
Private Member Functions
double toRadians (double degrees)
Private Attributes
double myIdentification
double myShapeIdentification
double myHeading
double isShowing
Pen myPen
List< Point2D > myTurtlePoints = new ArrayList<Point2D>()
Point2D myFirstPoint
Point2D myCurrPoint
Point2D myNextPoint
Static Private Attributes
static final int MYHEADING_CONVERSION_CONSTANT = 90
static final double PI = Math.PI
static final double RADIANS_TO_DEGREES = 180.0 / PI
Detailed Description
Definition at line 10 of file Turtle.java.
Constructor & Destructor Documentation
model.Turtle.Turtle (double identification)
Definition at line 28 of file Turtle.java.
Referenced by model.Turtle.compareTo().
Member Function Documentation
double model.Turtle.changePen (double pen)
Method to change whether the pen is up or down.
Parameters
pen : double representing whether the pen is up or down.
Definition at line 191 of file Turtle.java.
References model.Pen.getStatus(), and model.Pen.setPenStatus().
Referenced by commands.PenDownCommand.updateTurtle(), and commands.PenUpCommand.updateTurtle().
double model.Turtle.changeVisibility (double visible)
Method to change visibilty of turtle.
Parameters
visible : double representing visibility of turtle.
Definition at line 215 of file Turtle.java.
References model.Turtle.isShowing.
Referenced by commands.IsShowingCommand.executeCommand(), commands.ShowTurtleCommand.updateTurtle(), and commands.HideTurtleCommand.updateTurtle().
int model.Turtle.compareTo (Object obj)
override of compareTo, don't think it's used
Parameters
obj : what is being compared to.
Definition at line 45 of file Turtle.java.
References model.Turtle.myIdentification, and model.Turtle.Turtle().
double model.Turtle.getHeading ()
Method to return current heading.
Definition at line 122 of file Turtle.java.
References model.Turtle.myHeading.
Referenced by commands.HeadingCommand.executeCommand(), and view.panes.ViewPaneModule.updateTurtle().
double model.Turtle.getID ()
Method to get the ID of the turtle
Definition at line 292 of file Turtle.java.
References model.Turtle.myIdentification.
Referenced by commands.IDCommand.executeCommand(), and view.panes.ViewPaneModule.updateTurtle().
void model.Turtle.getmyCurr ()
Method to return the point the current
Definition at line 74 of file Turtle.java.
Referenced by model.Turtle.setXAndY(), model.Turtle.towards(), and model.Turtle.updatePosition().
Point2D model.Turtle.getNewLocation ()
Method to return where the turtle is going to be in the future.
Definition at line 225 of file Turtle.java.
Referenced by commands.YCoordinateCommand.executeCommand(), commands.XCoordinateCommand.executeCommand(), view.panes.ViewPaneModule.updateTurtle(), and view.panes.ViewPaneModule.wrapping().
Color model.Turtle.getPenColor ()
Method to get the color of the pen
Definition at line 285 of file Turtle.java.
References model.Pen.getPenColor().
Referenced by commands.GetPenColorCommand.executeCommand(), and view.panes.ViewPaneModule.updateTurtle().
double model.Turtle.getPenDash ()
Method to get whether the pen is dashed or solid
Definition at line 256 of file Turtle.java.
References model.Pen.getDash().
Referenced by view.panes.ViewPaneModule.updateTurtle().
double model.Turtle.getPenSize ()
Method to get the size of the pen
Definition at line 249 of file Turtle.java.
References model.Pen.getSize().
double model.Turtle.getPenStatus ()
Method to get the status of the pen
Definition at line 242 of file Turtle.java.
References model.Pen.getStatus().
Referenced by commands.IsPenDownCommand.executeCommand(), view.panes.ViewPaneModule.updateTurtle(), and view.panes.ViewPaneModule.wrapping().
Point2D model.Turtle.getPrevLocation ()
Method to return where the turtle was one step before
Definition at line 232 of file Turtle.java.
References model.Turtle.myFirstPoint.
Referenced by view.panes.ViewPaneModule.updateTurtle().
double model.Turtle.getShape ()
Method to get the shape of the turtle
Definition at line 278 of file Turtle.java.
References model.Turtle.myShapeIdentification.
Referenced by view.TurtleDraw.drawTurtle(), and commands.GetShapeCommand.executeCommand().
double model.Turtle.getShowing ()
Method to see if the turtle is showing
Definition at line 263 of file Turtle.java.
References model.Turtle.isShowing.
Map model.Turtle.getStats ()
Method to return a map containing various stats of the turtle
Definition at line 308 of file Turtle.java.
double model.Turtle.setHeading (double degree)
Method to set heading to a specific angle.
Parameters
double degree : what it should be set to.
Definition at line 131 of file Turtle.java.
References model.Turtle.myHeading.
Referenced by commands.SetHeadingCommand.updateTurtle(), and commands.HomeCommand.updateTurtle().
double model.Turtle.setPenColor (double red, double green, double blue)
Method to set the color of the pen.
Parameters
red,green,blue : doubles representing the value of red,green, blue that should be in the new color.
Definition at line 205 of file Turtle.java.
References model.Pen.updateColor().
Referenced by commands.SetPenColorCommand.updateTurtle().
double model.Turtle.setPenDash (double dash)
Method to set whether the line is dashed or solid.
Parameters
double dash : whether or not line is dashed.
Definition at line 93 of file Turtle.java.
References model.Pen.updateDash().
Referenced by commands.SetPenDashCommand.updateTurtle().
double model.Turtle.setPenSize (double size)
Method to set pen size.
Parameters
double size : sets pen size by setting it in pen
Definition at line 83 of file Turtle.java.
References model.Pen.updateSize().
Referenced by commands.SetPenSizeCommand.updateTurtle().
void model.Turtle.setPenStatus (double d)
Method to set the status of the pen param@ d : double representing whether the pen is showing
Definition at line 300 of file Turtle.java.
Referenced by view.panes.ViewPaneModule.wrapping().
double model.Turtle.setShape (double shapeID)
Method to set the shape of the turtle
Definition at line 270 of file Turtle.java.
Referenced by commands.SetShapeCommand.updateTurtle().
double model.Turtle.setXAndY (double x, double y)
Method to set x and y coordinates of a turtle.
Parameters
x,y : doubles representing x and y coordinates.
Definition at line 171 of file Turtle.java.
References model.Turtle.getmyCurr().
Referenced by commands.SetPositionCommand.updateTurtle(), commands.HomeCommand.updateTurtle(), and view.panes.ViewPaneModule.wrapping().
double model.Turtle.toRadians (double degrees) private
Method to convert degrees to radians.
Parameters
degrees : the degrees that should be converted
Definition at line 104 of file Turtle.java.
Referenced by model.Turtle.updatePosition().
double model.Turtle.towards (double x, double y)
Method to make the turtle face a given point.
Parameters
x,y : two doubles representing x and y coordinates.
Definition at line 143 of file Turtle.java.
References model.Turtle.getmyCurr(), model.Turtle.myHeading, and model.Turtle.MYHEADING_CONVERSION_CONSTANT.
Referenced by commands.SetTowardsCommand.updateTurtle().
double model.Turtle.updateHeading (double degree)
Method to update the heading of the turtle.
Parameters
double degree : double of what should be added to current heading.
Definition at line 113 of file Turtle.java.
Referenced by commands.RightCommand.updateTurtle(), and commands.LeftCommand.updateTurtle().
double model.Turtle.updatePosition (double forward)
Method to update the position of the turtle.
Parameters
doubel forward : how far in current direction you should move.
Definition at line 60 of file Turtle.java.
References model.Turtle.getmyCurr(), model.Turtle.myCurrPoint, and model.Turtle.toRadians().
Referenced by commands.BackwardCommand.updateTurtle(), and commands.ForwardCommand.updateTurtle().
Member Data Documentation
double model.Turtle.isShowing private
Definition at line 21 of file Turtle.java.
Referenced by model.Turtle.changeVisibility(), and model.Turtle.getShowing().
Point2D model.Turtle.myCurrPoint private
Definition at line 25 of file Turtle.java.
Referenced by model.Turtle.updatePosition().
Point2D model.Turtle.myFirstPoint private
Definition at line 24 of file Turtle.java.
Referenced by model.Turtle.getPrevLocation().
double model.Turtle.myHeading private
Definition at line 20 of file Turtle.java.
Referenced by model.Turtle.getHeading(), model.Turtle.setHeading(), and model.Turtle.towards().
final int model.Turtle.MYHEADING_CONVERSION_CONSTANT = 90 static private
Class of Turtle, the object that is seen on the screen represented as a turtle.
Definition at line 15 of file Turtle.java.
Referenced by model.Turtle.towards().
double model.Turtle.myIdentification private
Definition at line 18 of file Turtle.java.
Referenced by model.Turtle.compareTo(), and model.Turtle.getID().
Point2D model.Turtle.myNextPoint private
Definition at line 26 of file Turtle.java.
Pen model.Turtle.myPen private
Definition at line 22 of file Turtle.java.
double model.Turtle.myShapeIdentification private
Definition at line 19 of file Turtle.java.
Referenced by model.Turtle.getShape().
List<Point2D> model.Turtle.myTurtlePoints = new ArrayList<Point2D>() private
Definition at line 23 of file Turtle.java.
final double model.Turtle.PI = Math.PI static private
Definition at line 16 of file Turtle.java.
final double model.Turtle.RADIANS_TO_DEGREES = 180.0 / PI static private
Definition at line 17 of file Turtle.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/model/Turtle.java