slogo_team14: view.panes.PenPane Class Reference
view.panes.PenPane Class Reference
Public Member Functions
PenPane (CommandString cs)
VBox getPenPane ()
void newTurtle ()
void setPenStyle (int i)
ChoiceBox makeMenu ()
void changePenColor ()
Private Member Functions
void setPenWidth ()
Button makeButton (String property, EventHandler< ActionEvent > handler)
void setPenDash ()
ColorPicker makeColorPicker (String property, EventHandler< ActionEvent > handler)
Private Attributes
VBox myVbox = new VBox()
CommandString myCommandString
CheckBox myPenToggle = new CheckBox("Toggle PenUp")
ColorPicker myColorPicker
ChoiceBox< String > myPenStyles = new ChoiceBox<String>()
TextField myPenWidthTextField = new TextField("double from 0 to 1")
TextField myPenDashTextField = new TextField("double from 0 to 1")
Static Private Attributes
static final String[] PENSTYLE
Detailed Description
Allows properties of the Pen for a turtle to be configured graphically through the user interface.
Author
Team 14
Definition at line 28 of file PenPane.java.
Constructor & Destructor Documentation
view.panes.PenPane.PenPane (CommandString cs)
Definition at line 39 of file PenPane.java.
References view.panes.PenPane.changePenColor(), view.panes.PenPane.makeButton(), view.panes.PenPane.makeColorPicker(), view.panes.PenPane.makeMenu(), view.CommandString.setCommand(), view.panes.PenPane.setPenDash(), view.panes.PenPane.setPenWidth(), and view.Constants.SETTING.
Member Function Documentation
void view.panes.PenPane.changePenColor ()
Changes the color of the pen using a color picker
Definition at line 181 of file PenPane.java.
References view.CommandString.setCommand().
Referenced by view.panes.PenPane.PenPane().
VBox view.panes.PenPane.getPenPane ()
Returns the VBox containing the PenPane
Returns
VBox containing the PenPane
Definition at line 72 of file PenPane.java.
References view.panes.PenPane.myVbox.
Referenced by view.panes.TurtleControllerPaneModule.TurtleControllerPaneModule().
Button view.panes.PenPane.makeButton (String property, EventHandler< ActionEvent > handler) private
Button Factory
Parameters
property String label for button
handler EventHandler for the button
Returns
Completed Button
Definition at line 96 of file PenPane.java.
Referenced by view.panes.PenPane.PenPane().
ColorPicker view.panes.PenPane.makeColorPicker (String property, EventHandler< ActionEvent > handler) private
ColorPicker Factory
Parameters
property String label for ColorPicker
handler EventHandler for ColorPicker
Returns
Completed ColorPicker
Definition at line 151 of file PenPane.java.
Referenced by view.panes.PenPane.PenPane().
ChoiceBox view.panes.PenPane.makeMenu ()
Makes the menu for the types of Pen Styles
Returns
ChoiceBox containing the types of Pen Styles
Definition at line 164 of file PenPane.java.
References view.panes.PenPane.setPenStyle().
Referenced by view.panes.PenPane.PenPane().
void view.panes.PenPane.newTurtle ()
Sets the toggle correctly when a new turtle is made
Definition at line 119 of file PenPane.java.
Referenced by view.panes.TurtleControllerPaneModule.makeTurtle().
void view.panes.PenPane.setPenDash () private
Sets the Dash Style of the Pen
Definition at line 107 of file PenPane.java.
References view.CommandString.setCommand(), and view.Constants.SETTING.
Referenced by view.panes.PenPane.PenPane().
void view.panes.PenPane.setPenStyle (int i)
Sets the style of the pen
Parameters
i int representing the style of the pen
Definition at line 130 of file PenPane.java.
References view.CommandString.setCommand(), and view.Constants.SETTING.
Referenced by view.panes.PenPane.makeMenu().
void view.panes.PenPane.setPenWidth () private
Sets the width of the Pen
Definition at line 79 of file PenPane.java.
References view.CommandString.setCommand(), and view.Constants.SETTING.
Referenced by view.panes.PenPane.PenPane().
Member Data Documentation
ColorPicker view.panes.PenPane.myColorPicker private
Definition at line 32 of file PenPane.java.
CommandString view.panes.PenPane.myCommandString private
Definition at line 30 of file PenPane.java.
TextField view.panes.PenPane.myPenDashTextField = new TextField("double from 0 to 1") private
Definition at line 35 of file PenPane.java.
ChoiceBox<String> view.panes.PenPane.myPenStyles = new ChoiceBox<String>() private
Definition at line 33 of file PenPane.java.
CheckBox view.panes.PenPane.myPenToggle = new CheckBox("Toggle PenUp") private
Definition at line 31 of file PenPane.java.
TextField view.panes.PenPane.myPenWidthTextField = new TextField("double from 0 to 1") private
Definition at line 34 of file PenPane.java.
VBox view.panes.PenPane.myVbox = new VBox() private
Definition at line 29 of file PenPane.java.
Referenced by view.panes.PenPane.getPenPane().
final String [] view.panes.PenPane.PENSTYLE static private
Initial value:
= new String[] { "Thin", "Thick", "Thicker", "Thickest",
            "Dashed", "Dotted" }
Definition at line 36 of file PenPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/panes/PenPane.java