slogo_team14: view.panes.ViewPaneModule Class Reference
view.panes.ViewPaneModule Class Reference
Public Member Functions
ViewPaneModule (ImagePalette ip)
void updateView (Model m)
BorderPane addPane (BorderPane p)
void changeGridVisibility ()
Set< Turtle > getTurtles ()
void toggleActive (boolean b)
Public Member Functions inherited from view.panes.PaneModule
abstract BorderPane addPane (BorderPane p)
Public Attributes
boolean gridVisible = true
Private Member Functions
void createGrid (Color c)
void makeStamps ()
void eraseStamps ()
void updateTurtle (Turtle t)
void wrapping (Turtle t)
void DisplayStats (Turtle t)
void updateBGColor (String RGB)
String toRGB (Color c)
Private Attributes
Color myBackColor
String RGB
Pane myPane = new Pane()
TurtleDraw myDraw
Point2D myCurrentPoint = new Point2D(0, 0)
List< Line > myGrid = new ArrayList<Line>()
Color defColor = Color.LIGHTGRAY
Set< Turtle > myTurtles
ImagePalette myImagePalette
Map< Integer, ImageView > myIcons = new HashMap<Integer, ImageView>()
boolean mySelectorCheck = false
Set< Turtle > myActiveTurtles
Model myModel
List< ImageView > myStamps = new ArrayList<ImageView>()
Detailed Description
Responsible for drawing the graphical representation of the turtles movement as its state changes using Observable. Calls on the Draw class to update the graphical representation stored in View when the status of a turtle changes.
Author
Team 14
Definition at line 29 of file ViewPaneModule.java.
Constructor & Destructor Documentation
view.panes.ViewPaneModule.ViewPaneModule (ImagePalette ip)
Constructor method called from UserInterface.java
Definition at line 50 of file ViewPaneModule.java.
References view.panes.ViewPaneModule.createGrid(), view.Constants.DEFAULT_BGCOLOR, view.panes.ViewPaneModule.toRGB(), view.panes.ViewPaneModule.updateBGColor(), and view.Constants.VIEW_DEFAULT_DIMENSION.
Member Function Documentation
BorderPane view.panes.ViewPaneModule.addPane (BorderPane p)
Adds the pane to the BorderPane
Definition at line 88 of file ViewPaneModule.java.
void view.panes.ViewPaneModule.changeGridVisibility ()
Toggles the visibility of the Grid
Definition at line 119 of file ViewPaneModule.java.
References view.panes.ViewPaneModule.gridVisible.
Referenced by view.panes.ButtonPaneModule.toggleGrid().
void view.panes.ViewPaneModule.createGrid (Color c) private
Creates a Grid
Parameters
c Color of the grid
Definition at line 99 of file ViewPaneModule.java.
References view.Constants.VIEW_DEFAULT_DIMENSION.
Referenced by view.panes.ViewPaneModule.ViewPaneModule().
void view.panes.ViewPaneModule.DisplayStats (Turtle t) private
Definition at line 201 of file ViewPaneModule.java.
void view.panes.ViewPaneModule.eraseStamps () private
Clears all stamps
Definition at line 143 of file ViewPaneModule.java.
References view.TurtleDraw.hideTurtle().
Referenced by view.panes.ViewPaneModule.updateView().
Set<Turtle> view.panes.ViewPaneModule.getTurtles ()
Gets the set of Turtles
Returns
Set of Turtles
Definition at line 238 of file ViewPaneModule.java.
References view.panes.ViewPaneModule.myTurtles.
void view.panes.ViewPaneModule.makeStamps () private
Makes a stamp of all currently active turtles
Definition at line 130 of file ViewPaneModule.java.
References view.TurtleDraw.drawTurtle(), view.TurtleDraw.moveTurtle(), view.TurtleDraw.setAngle(), and view.TurtleDraw.showTurtle().
Referenced by view.panes.ViewPaneModule.updateView().
void view.panes.ViewPaneModule.toggleActive (boolean b)
Toggles that active turtles should have a graphical identifier.
Parameters
b Boolean representing whether turtles need a graphical identifier
Definition at line 246 of file ViewPaneModule.java.
References view.panes.ViewPaneModule.updateView().
Referenced by view.panes.TurtleSelectorPane.TurtleSelectorPane().
String view.panes.ViewPaneModule.toRGB (Color c) private
Takes a color and turns into a RBG String
Parameters
c Color
Returns
RGB String representing the Color
Definition at line 222 of file ViewPaneModule.java.
Referenced by view.panes.ViewPaneModule.updateView(), and view.panes.ViewPaneModule.ViewPaneModule().
void view.panes.ViewPaneModule.updateBGColor (String RGB) private
Updates the background color of the View
Parameters
RGB String representing the RBG value to set the background to
Definition at line 211 of file ViewPaneModule.java.
Referenced by view.panes.ViewPaneModule.updateView(), and view.panes.ViewPaneModule.ViewPaneModule().
void view.panes.ViewPaneModule.updateTurtle (Turtle t) private
Updates the drawing state of a turtle
Parameters
t Turtle to have it's state drawn to the frontend
Definition at line 156 of file ViewPaneModule.java.
References view.TurtleDraw.drawLine(), view.TurtleDraw.drawTurtle(), model.Turtle.getHeading(), model.Turtle.getID(), model.Turtle.getNewLocation(), model.Turtle.getPenColor(), model.Turtle.getPenDash(), model.Turtle.getPenStatus(), model.Turtle.getPrevLocation(), view.TurtleDraw.hideTurtle(), view.TurtleDraw.moveTurtle(), view.TurtleDraw.myPath, view.panes.ViewPaneModule.mySelectorCheck, view.TurtleDraw.setAngle(), and view.TurtleDraw.showTurtle().
Referenced by view.panes.ViewPaneModule.updateView().
void view.panes.ViewPaneModule.updateView (Model m)
Updates the view with the Model
Parameters
m Model containing the Turtles and current state of the simulation
Definition at line 67 of file ViewPaneModule.java.
References view.panes.ViewPaneModule.eraseStamps(), model.TurtleSetManager.getActiveTurtles(), model.TurtleSetManager.getAllTurtles(), model.Model.getBackgroundColor(), model.Model.getStamp(), model.Model.getTurtleManager(), view.panes.ViewPaneModule.makeStamps(), model.Model.setStamp(), view.panes.ViewPaneModule.toRGB(), view.panes.ViewPaneModule.updateBGColor(), and view.panes.ViewPaneModule.updateTurtle().
Referenced by model.Model.notifyView(), and view.panes.ViewPaneModule.toggleActive().
void view.panes.ViewPaneModule.wrapping (Turtle t) private
Attempt at wrapping the View. Doesn't fully work
Parameters
t Turtle that needs to be wrapped
Definition at line 183 of file ViewPaneModule.java.
References model.Turtle.getNewLocation(), model.Turtle.getPenStatus(), model.Turtle.setPenStatus(), model.Turtle.setXAndY(), and view.Constants.VIEW_DEFAULT_DIMENSION.
Member Data Documentation
Color view.panes.ViewPaneModule.defColor = Color.LIGHTGRAY private
Definition at line 38 of file ViewPaneModule.java.
boolean view.panes.ViewPaneModule.gridVisible = true
Definition at line 31 of file ViewPaneModule.java.
Referenced by view.panes.ViewPaneModule.changeGridVisibility().
Set<Turtle> view.panes.ViewPaneModule.myActiveTurtles private
Definition at line 43 of file ViewPaneModule.java.
Color view.panes.ViewPaneModule.myBackColor private
Definition at line 32 of file ViewPaneModule.java.
Point2D view.panes.ViewPaneModule.myCurrentPoint = new Point2D(0, 0) private
Definition at line 36 of file ViewPaneModule.java.
TurtleDraw view.panes.ViewPaneModule.myDraw private
Definition at line 35 of file ViewPaneModule.java.
List<Line> view.panes.ViewPaneModule.myGrid = new ArrayList<Line>() private
Definition at line 37 of file ViewPaneModule.java.
Map<Integer, ImageView> view.panes.ViewPaneModule.myIcons = new HashMap<Integer, ImageView>() private
Definition at line 41 of file ViewPaneModule.java.
ImagePalette view.panes.ViewPaneModule.myImagePalette private
Definition at line 40 of file ViewPaneModule.java.
Model view.panes.ViewPaneModule.myModel private
Definition at line 44 of file ViewPaneModule.java.
Pane view.panes.ViewPaneModule.myPane = new Pane() private
Definition at line 34 of file ViewPaneModule.java.
boolean view.panes.ViewPaneModule.mySelectorCheck = false private
Definition at line 42 of file ViewPaneModule.java.
Referenced by view.panes.ViewPaneModule.updateTurtle().
List<ImageView> view.panes.ViewPaneModule.myStamps = new ArrayList<ImageView>() private
Definition at line 45 of file ViewPaneModule.java.
Set<Turtle> view.panes.ViewPaneModule.myTurtles private
Definition at line 39 of file ViewPaneModule.java.
Referenced by view.panes.ViewPaneModule.getTurtles().
String view.panes.ViewPaneModule.RGB private
Definition at line 33 of file ViewPaneModule.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/view/panes/ViewPaneModule.java