slogo_team14: model.TurtleSetManager Class Reference
model.TurtleSetManager Class Reference
Public Member Functions
TurtleSetManager (Set< Turtle > turtles)
void addTurtleCollection (Set< Turtle > newSet)
void regulateTurtleDepth (int finalLength)
void addTurtle (int id)
Set< Turtle > getActiveTurtles ()
Set< Turtle > getAllTurtles ()
int getStackLength ()
Private Attributes
Stack< Set< Turtle > > myStack
Set< Turtle > mySet
Detailed Description
Class the contains various lists of turtles, used to manage scope of the turtle
Definition at line 10 of file TurtleSetManager.java.
Constructor & Destructor Documentation
model.TurtleSetManager.TurtleSetManager (Set< Turtle > turtles)
Definition at line 15 of file TurtleSetManager.java.
Member Function Documentation
void model.TurtleSetManager.addTurtle (int id)
Method to add a turtle to the whole collection of turtles, don't think it's used.
Parameters
id : adds new turtle with ID int id.
Definition at line 52 of file TurtleSetManager.java.
void model.TurtleSetManager.addTurtleCollection (Set< Turtle > newSet)
Method to add a set to the current stack of sets of turtles.
Parameters
newSet : the set to be added.
Definition at line 28 of file TurtleSetManager.java.
Referenced by commands.TellCommand.executeCommand().
Set<Turtle> model.TurtleSetManager.getActiveTurtles ()
Method to return collection of currently active turtles.
Definition at line 59 of file TurtleSetManager.java.
Referenced by commands.Command.executeCommand(), commands.Command.getFirstTurtle(), and view.panes.ViewPaneModule.updateView().
Set<Turtle> model.TurtleSetManager.getAllTurtles ()
Method to return collection of all turtles
Definition at line 66 of file TurtleSetManager.java.
References model.TurtleSetManager.mySet.
Referenced by commands.AskWithCommand.executeCommand(), commands.TellCommand.executeCommand(), and view.panes.ViewPaneModule.updateView().
int model.TurtleSetManager.getStackLength ()
Method to get the length of the stack, used in regulatedepth for ease in typing.
Definition at line 74 of file TurtleSetManager.java.
Referenced by commands.AskCommand.executeCommand(), commands.AskWithCommand.executeCommand(), and model.TurtleSetManager.regulateTurtleDepth().
void model.TurtleSetManager.regulateTurtleDepth (int finalLength)
Method to regulate the depth of the stack.
Parameters
finalLength : integer representing the length the stack should be when this is called.
Definition at line 39 of file TurtleSetManager.java.
References model.TurtleSetManager.getStackLength().
Referenced by commands.AskCommand.executeCommand(), and commands.AskWithCommand.executeCommand().
Member Data Documentation
Set<Turtle> model.TurtleSetManager.mySet private
Definition at line 13 of file TurtleSetManager.java.
Referenced by model.TurtleSetManager.getAllTurtles().
Stack<Set<Turtle> > model.TurtleSetManager.myStack private
Definition at line 12 of file TurtleSetManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team14/repository/src/model/TurtleSetManager.java